version: "3.7"
services:
  mysql:
    image: arm64v8/mysql
    restart: always
    container_name: mysql
    command:
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${MYSQL_TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/mysql-metaverse-init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env


volumes:
  mysql_data:
  postgres_data:
